<?php

namespace Cx\Modules\Block\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RelLangContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelLangContentRepository extends EntityRepository
{
}
