<?php

namespace Cx\Model\Proxies\__CG__\Cx\Modules\Shop\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \Cx\Modules\Shop\Model\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

        return parent::__get($name);
    }





    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'locale', 'id', 'picture', 'distribution', 'normalprice', 'resellerprice', 'stock', 'stockVisible', 'discountprice', 'discountActive', 'active', 'b2b', 'b2c', 'dateStart', 'dateEnd', 'manufacturerId', 'ord', 'vatId', 'weight', 'flags', 'groupId', 'articleId', 'minimumOrderQuantity', 'uri', 'short', 'long', 'name', 'keys', 'code', 'discountCoupons', 'orderItems', 'relProductAttributes', 'manufacturer', 'discountgroupCountName', 'articleGroup', 'vat', 'categories', 'userGroups', 'validators', 'virtual');
        }

        return array('__isInitialized__', 'locale', 'id', 'picture', 'distribution', 'normalprice', 'resellerprice', 'stock', 'stockVisible', 'discountprice', 'discountActive', 'active', 'b2b', 'b2c', 'dateStart', 'dateEnd', 'manufacturerId', 'ord', 'vatId', 'weight', 'flags', 'groupId', 'articleId', 'minimumOrderQuantity', 'uri', 'short', 'long', 'name', 'keys', 'code', 'discountCoupons', 'orderItems', 'relProductAttributes', 'manufacturer', 'discountgroupCountName', 'articleGroup', 'vat', 'categories', 'userGroups', 'validators', 'virtual');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTranslatableLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTranslatableLocale', array($locale));

        return parent::setTranslatableLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture($picture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', array($picture));

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', array());

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistribution($distribution)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistribution', array($distribution));

        return parent::setDistribution($distribution);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistribution()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistribution', array());

        return parent::getDistribution();
    }

    /**
     * {@inheritDoc}
     */
    public function setNormalprice($normalprice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNormalprice', array($normalprice));

        return parent::setNormalprice($normalprice);
    }

    /**
     * {@inheritDoc}
     */
    public function getNormalprice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNormalprice', array());

        return parent::getNormalprice();
    }

    /**
     * {@inheritDoc}
     */
    public function setResellerprice($resellerprice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResellerprice', array($resellerprice));

        return parent::setResellerprice($resellerprice);
    }

    /**
     * {@inheritDoc}
     */
    public function getResellerprice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResellerprice', array());

        return parent::getResellerprice();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock($stock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', array($stock));

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', array());

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setStockVisible($stockVisible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStockVisible', array($stockVisible));

        return parent::setStockVisible($stockVisible);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockVisible', array());

        return parent::getStockVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountprice($discountprice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountprice', array($discountprice));

        return parent::setDiscountprice($discountprice);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountprice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountprice', array());

        return parent::getDiscountprice();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountActive($discountActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountActive', array($discountActive));

        return parent::setDiscountActive($discountActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountActive', array());

        return parent::getDiscountActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setB2b($b2b)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setB2b', array($b2b));

        return parent::setB2b($b2b);
    }

    /**
     * {@inheritDoc}
     */
    public function getB2b()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getB2b', array());

        return parent::getB2b();
    }

    /**
     * {@inheritDoc}
     */
    public function setB2c($b2c)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setB2c', array($b2c));

        return parent::setB2c($b2c);
    }

    /**
     * {@inheritDoc}
     */
    public function getB2c()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getB2c', array());

        return parent::getB2c();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateStart($dateStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateStart', array($dateStart));

        return parent::setDateStart($dateStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateStart', array());

        return parent::getDateStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEnd($dateEnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEnd', array($dateEnd));

        return parent::setDateEnd($dateEnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEnd', array());

        return parent::getDateEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturerId($manufacturerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturerId', array($manufacturerId));

        return parent::setManufacturerId($manufacturerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturerId', array());

        return parent::getManufacturerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrd($ord)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrd', array($ord));

        return parent::setOrd($ord);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrd', array());

        return parent::getOrd();
    }

    /**
     * {@inheritDoc}
     */
    public function setVatId($vatId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVatId', array($vatId));

        return parent::setVatId($vatId);
    }

    /**
     * {@inheritDoc}
     */
    public function getVatId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVatId', array());

        return parent::getVatId();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeight($weight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeight', array($weight));

        return parent::setWeight($weight);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeight', array());

        return parent::getWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlags($flags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlags', array($flags));

        return parent::setFlags($flags);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlags', array());

        return parent::getFlags();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroupId($groupId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroupId', array($groupId));

        return parent::setGroupId($groupId);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupId', array());

        return parent::getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticleId($articleId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticleId', array($articleId));

        return parent::setArticleId($articleId);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticleId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticleId', array());

        return parent::getArticleId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinimumOrderQuantity($minimumOrderQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinimumOrderQuantity', array($minimumOrderQuantity));

        return parent::setMinimumOrderQuantity($minimumOrderQuantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinimumOrderQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinimumOrderQuantity', array());

        return parent::getMinimumOrderQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUri($uri)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUri', array($uri));

        return parent::setUri($uri);
    }

    /**
     * {@inheritDoc}
     */
    public function getUri()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUri', array());

        return parent::getUri();
    }

    /**
     * {@inheritDoc}
     */
    public function setShort($short)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShort', array($short));

        return parent::setShort($short);
    }

    /**
     * {@inheritDoc}
     */
    public function getShort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShort', array());

        return parent::getShort();
    }

    /**
     * {@inheritDoc}
     */
    public function setLong($long)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLong', array($long));

        return parent::setLong($long);
    }

    /**
     * {@inheritDoc}
     */
    public function getLong()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLong', array());

        return parent::getLong();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeys($keys)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeys', array($keys));

        return parent::setKeys($keys);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeys()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeys', array());

        return parent::getKeys();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function addDiscountCoupon(\Cx\Modules\Shop\Model\Entity\DiscountCoupon $discountCoupon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDiscountCoupon', array($discountCoupon));

        return parent::addDiscountCoupon($discountCoupon);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDiscountCoupon(\Cx\Modules\Shop\Model\Entity\DiscountCoupon $discountCoupon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDiscountCoupon', array($discountCoupon));

        return parent::removeDiscountCoupon($discountCoupon);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountCoupons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountCoupons', array());

        return parent::getDiscountCoupons();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderItem(\Cx\Modules\Shop\Model\Entity\OrderItem $orderItem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderItem', array($orderItem));

        return parent::addOrderItem($orderItem);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderItem(\Cx\Modules\Shop\Model\Entity\OrderItem $orderItem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderItem', array($orderItem));

        return parent::removeOrderItem($orderItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderItems', array());

        return parent::getOrderItems();
    }

    /**
     * {@inheritDoc}
     */
    public function addRelProductAttribute(\Cx\Modules\Shop\Model\Entity\RelProductAttribute $relProductAttribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelProductAttribute', array($relProductAttribute));

        return parent::addRelProductAttribute($relProductAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelProductAttribute(\Cx\Modules\Shop\Model\Entity\RelProductAttribute $relProductAttribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelProductAttribute', array($relProductAttribute));

        return parent::removeRelProductAttribute($relProductAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelProductAttributes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelProductAttributes', array());

        return parent::getRelProductAttributes();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturer(\Cx\Modules\Shop\Model\Entity\Manufacturer $manufacturer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturer', array($manufacturer));

        return parent::setManufacturer($manufacturer);
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturer', array());

        return parent::getManufacturer();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountgroupCountName(\Cx\Modules\Shop\Model\Entity\DiscountgroupCountName $discountgroupCountName = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountgroupCountName', array($discountgroupCountName));

        return parent::setDiscountgroupCountName($discountgroupCountName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountgroupCountName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountgroupCountName', array());

        return parent::getDiscountgroupCountName();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticleGroup(\Cx\Modules\Shop\Model\Entity\ArticleGroup $articleGroup = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticleGroup', array($articleGroup));

        return parent::setArticleGroup($articleGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticleGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticleGroup', array());

        return parent::getArticleGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setVat(\Cx\Modules\Shop\Model\Entity\Vat $vat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVat', array($vat));

        return parent::setVat($vat);
    }

    /**
     * {@inheritDoc}
     */
    public function getVat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVat', array());

        return parent::getVat();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\Cx\Modules\Shop\Model\Entity\Category $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', array($category));

        return parent::addCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategory(\Cx\Modules\Shop\Model\Entity\Category $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategory', array($category));

        return parent::removeCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', array());

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserGroup(\Cx\Core\User\Model\Entity\Group $userGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserGroup', array($userGroup));

        return parent::addUserGroup($userGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserGroup(\Cx\Core\User\Model\Entity\Group $userGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserGroup', array($userGroup));

        return parent::removeUserGroup($userGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserGroups', array());

        return parent::getUserGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getJsArray($groupCustomerId = 0, $isReseller = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJsArray', array($groupCustomerId, $isReseller));

        return parent::getJsArray($groupCustomerId, $isReseller);
    }

    /**
     * {@inheritDoc}
     */
    public function getComponentController()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComponentController', array());

        return parent::getComponentController();
    }

    /**
     * {@inheritDoc}
     */
    public function setVirtual($virtual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVirtual', array($virtual));

        return parent::setVirtual($virtual);
    }

    /**
     * {@inheritDoc}
     */
    public function isVirtual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVirtual', array());

        return parent::isVirtual();
    }

    /**
     * {@inheritDoc}
     */
    public function initializeValidators()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'initializeValidators', array());

        return parent::initializeValidators();
    }

    /**
     * {@inheritDoc}
     */
    public function validate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validate', array());

        return parent::validate();
    }

    /**
     * {@inheritDoc}
     */
    public function __call($methodName, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($methodName, $arguments));

        return parent::__call($methodName, $arguments);
    }

}
