<?php

namespace Cx\Modules\Shop\Model\Repository;

/**
 * LsvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LsvRepository extends \Doctrine\ORM\EntityRepository
{
}
