<?php

namespace Cx\Modules\Shop\Model\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    const STATUS_PENDING   = 0;
    const STATUS_CONFIRMED = 1;
    const STATUS_DELETED   = 2;
    const STATUS_CANCELLED = 3;
    const STATUS_COMPLETED = 4;
    const STATUS_PAID      = 5;
    const STATUS_SHIPPED   = 6;

    const STATUS_MAX = 6;

    /**
     * Get an array with all status values
     */
    public function getStatusValues()
    {
        global $_ARRAYLANG;

        $statusValues = array();
        for ($i = 0; $i <= $this::STATUS_MAX; $i++) {
            array_push(
                $statusValues,
                $_ARRAYLANG['TXT_SHOP_ORDER_STATUS_' . $i]
            );
        }

        return $statusValues;
    }
}