<?php

namespace Cx\Modules\Shop\Model\Repository;

/**
 * PaymentProcessorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentProcessorRepository extends \Doctrine\ORM\EntityRepository
{
}
