<?php

namespace Cx\Modules\Shop\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentProcessorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentProcessorsRepository extends EntityRepository
{
}
