<?php

namespace Cx\Modules\Shop\Model\Repository;

/**
 * RelCountriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
