<?php

namespace Cx\Modules\Shop\Model\Repository;

/**
 * RelDiscountGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelDiscountGroupRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Returns the customer/article type discount rate to be applied
     * for the given group IDs
     *
     * Frontend use only.
     * @param   integer   $groupCustomerId    The customer group ID
     * @param   integer   $groupArticleId     The article group ID
     * @return  float                         The discount rate, if applicable,
     *                                        0 (zero) otherwise
     */
    function getDiscountRateCustomer($groupCustomerId, $groupArticleId)
    {
        $rate = $this->findOneBy(
            array(
                'customerGroupId' => $groupCustomerId,
                'articleGroupId' => $groupArticleId
            )
        );

        if (!empty($rate)) {
            return $rate->getRate();
        }
        return 0;
    }

    /**
     * Returns an array with all the customer/article type discount rates.
     *
     * The array has the structure
     *  array(
     *    customerGroupId => array(
     *      articleGroupId => discountRate,
     *      ...
     *    ),
     *    ...
     *  );
     * @return  array The discount rate array on success, empty array otherwise
     */
    function getDiscountRateCustomerArray()
    {
        $relDiscountGroups = $this->findAll();

        $arrDiscountRateCustomer = array();
        foreach ($relDiscountGroups as $relDiscountGroup) {
            $arrDiscountRateCustomer[$relDiscountGroup->getCustomerGroupId()]
            [$relDiscountGroup->getArticleGroupId()] =
                $relDiscountGroup->getRate();
        }

        return $arrDiscountRateCustomer;
    }

    /**
     * Store the customer/article group discounts in the database.
     *
     * Backend use only.
     * The array argument has the structure
     *  array(
     *    customerGroupId => array(
     *      articleGroupId => discountRate,
     *      ...
     *    ),
     *    ...
     *  );
     * @param   array     $arrDiscountRate  The array of discount rates
     *
     * @throws \Doctrine\ORM\OptimisticLockException handle orm interaction
     */
    function storeDiscountCustomer($arrDiscountRate)
    {
        $articleGroupRepo = $this->_em->getRepository(
            'Cx\Modules\Shop\Model\Entity\ArticleGroup'
        );
        $customerGroupRepo = $this->_em->getRepository(
            'Cx\Modules\Shop\Model\Entity\CustomerGroup'
        );
        foreach ($arrDiscountRate as $customerGroupId => $articleGroup) {
            foreach ($articleGroup as $articleGroupId => $discountRate) {
                $discountGroup = $this->findOneBy(
                    array(
                        'articleGroupId' => $articleGroupId,
                        'customerGroupId' => $customerGroupId
                    )
                );

                if (empty($discountGroup)) {
                    $discountGroup =
                        new \Cx\Modules\Shop\Model\Entity\RelDiscountGroup();
                    $discountGroup->setArticleGroupId($articleGroupId);
                    $discountGroup->setArticleGroup(
                        $articleGroupRepo->find($articleGroupId)
                    );
                    $discountGroup->setCustomerGroupId($customerGroupId);
                    $discountGroup->setCustomerGroup(
                        $customerGroupRepo->find($customerGroupId)
                    );
                }
                $discountGroup->setRate($discountRate);
                $this->_em->persist($discountGroup);
            }
        }
        $this->_em->flush();
    }
}
