<?php

namespace Cx\Modules\Shop\Model\Repository;

/**
 * RelProductAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelProductAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
