<?php

namespace Cx\Core\User\Model\Repository;

/**
 * TwofactorAuthenticationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwofactorAuthenticationRepository extends \Doctrine\ORM\EntityRepository
{
}